# Generated by Django 6.0 on 2026-01-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_confirmationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
