# Generated by Django 6.0 on 2026-01-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_confirmationcode_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='is_confirmed',
        ),
    ]
